[package]
name = "collector-bin"
description = "Collector Windows Service binary (collector.exe)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "collector"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
collector.workspace = true
tokio.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows-service = "0.8"
